services:
  db:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: todolist
    ports:
      - "5433:5432" # если порт занят, поменяй слева на 5433 и см. ниже
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todolist"]
      interval: 3s
      timeout: 3s
      retries: 20

volumes:
  dbdata:
