// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {repo} from '../models';

export function CreateTask(arg1:repo.CreateTaskInput):Promise<Array<repo.Task>>;

export function ListTasks(arg1:string,arg2:string):Promise<Array<repo.Task>>;

export function RemoveTaskByID(arg1:number):Promise<Array<repo.Task>>;

export function ToggleComplete(arg1:number,arg2:boolean):Promise<Array<repo.Task>>;
