// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTodo(arg1) {
  return window['go']['main']['App']['AddTodo'](arg1);
}

export function ListTodos() {
  return window['go']['main']['App']['ListTodos']();
}

export function RemoveTodo(arg1) {
  return window['go']['main']['App']['RemoveTodo'](arg1);
}
