// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function ListTasks(arg1, arg2) {
  return window['go']['main']['App']['ListTasks'](arg1, arg2);
}

export function RemoveTaskByID(arg1) {
  return window['go']['main']['App']['RemoveTaskByID'](arg1);
}

export function ToggleComplete(arg1, arg2) {
  return window['go']['main']['App']['ToggleComplete'](arg1, arg2);
}
