// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTodo(arg1:string):Promise<Array<string>>;

export function ListTodos():Promise<Array<string>>;

export function RemoveTodo(arg1:number):Promise<Array<string>>;
