// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateTask(arg1:main.CreateTaskInput):Promise<Array<main.Task>>;

export function ListTasks(arg1:string,arg2:string):Promise<Array<main.Task>>;

export function RemoveTaskByID(arg1:number):Promise<Array<main.Task>>;

export function ToggleComplete(arg1:number,arg2:boolean):Promise<Array<main.Task>>;
